E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] failed while attempting to run meta for aten.roll.default
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] Traceback (most recent call last):
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_subclasses/fake_tensor.py", line 2384, in _dispatch_impl
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     r = func(*args, **kwargs)
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]         ^^^^^^^^^^^^^^^^^^^^^
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_ops.py", line 723, in __call__
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     return self._op(*args, **kwargs)
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_prims_common/wrappers.py", line 291, in _fn
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     result = fn(*args, **kwargs)
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]              ^^^^^^^^^^^^^^^^^^^
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_refs/__init__.py", line 3870, in roll
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     raise RuntimeError("`shifts` required")
E0204 13:46:44.644000 2147303 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] RuntimeError: `shifts` required
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] failed while attempting to run meta for aten.roll.default
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] Traceback (most recent call last):
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_subclasses/fake_tensor.py", line 2384, in _dispatch_impl
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     r = func(*args, **kwargs)
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]         ^^^^^^^^^^^^^^^^^^^^^
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_ops.py", line 723, in __call__
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     return self._op(*args, **kwargs)
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_prims_common/wrappers.py", line 291, in _fn
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     result = fn(*args, **kwargs)
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]              ^^^^^^^^^^^^^^^^^^^
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_refs/__init__.py", line 3870, in roll
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     raise RuntimeError("`shifts` required")
E0205 18:36:48.261000 180595 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] RuntimeError: `shifts` required
